unit TestMHAAddRecordAutomaticApheresis;

{  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested. }

interface

uses
  TestFramework, DateUtils, Dialogs, MHAAddRecordAutomaticApheresis, SysUtils,
  GetAdoQuery, Data.Win.ADODB, UCheckNull, Data.DB;

type
  // Test methods for class IMHAAddRecordAutomaticApheresis

  TestIMHAAddRecordAutomaticApheresis = class(TTestCase)
  strict private
    FIMHAAddRecordAutomaticApheresis: IMHAAddRecordAutomaticApheresis;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAddRecordPlasma;
    procedure TestAddRecordPlasmaDoza;
    procedure TestAddRecordPlasmaComponents;
    procedure TestAddRecordPlasmaDefect;
  end;

implementation

procedure TestIMHAAddRecordAutomaticApheresis.SetUp;
begin
  FIMHAAddRecordAutomaticApheresis:=TMHAAddRecordAutomaticApheresis.create;
end;

procedure TestIMHAAddRecordAutomaticApheresis.TearDown;
begin
  FIMHAAddRecordAutomaticApheresis := nil;
end;

procedure TestIMHAAddRecordAutomaticApheresis.TestAddRecordPlasma;
var
  AllStoredBlood: string;
  AllWholeBlood: string;
  ForLaboratoryResearch: string;
  SentToPreserving: string;
  VolumeDonors: string;
  Date: Extended;
begin
  FIMHAAddRecordAutomaticApheresis.AddRecordPlasma(Date, VolumeDonors, SentToPreserving,
      ForLaboratoryResearch, AllWholeBlood, AllStoredBlood);
end;

procedure TestIMHAAddRecordAutomaticApheresis.TestAddRecordPlasmaDoza;
var
  Volue600: string;
  Date: Extended;
begin
  FIMHAAddRecordAutomaticApheresis.AddRecordPlasmaDoza(Date, Volue600);
end;

procedure TestIMHAAddRecordAutomaticApheresis.TestAddRecordPlasmaComponents;
var
  TypeProduction: string;
  NumberDosesPlazma: string;
  VolumePlazma: string;
begin
  FIMHAAddRecordAutomaticApheresis.AddRecordPlasmaComponents(VolumePlazma, NumberDosesPlazma,
      TypeProduction);
end;

procedure TestIMHAAddRecordAutomaticApheresis.TestAddRecordPlasmaDefect;
var
  TypeOfDefect: string;
  NumberDosesDefects: string;
  VolumeDefects: string;
begin
  FIMHAAddRecordAutomaticApheresis.AddRecordPlasmaDefect(VolumeDefects, NumberDosesDefects,
      TypeOfDefect);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestIMHAAddRecordAutomaticApheresis.Suite);
end.

