unit TestMHAAutomaticApheresis;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, MFBitBtnEdit, Vcl.Grids, USCheckForExistenceOfRecord, Buttons,
  MHAAutomaticApheresis, MFBitBtnAdd, DateUtils, Dialogs, MFTitleLabel, Vcl.ComCtrls,
  Vcl.ExtCtrls, USCheckFillStringFields, MFStringGrid, MFEdit,
  BHAAddRecordAutomaticApheresis, USBlockMainMenu, USValueChecksOnTheAdequacy,
  Forms, Data.DB, StdCtrls, SysUtils, MFPanel, MFLabel, BHADeleteRecordAutomaticApheresis,
  BHAChangeRecordAutomaticApheresis, MFBitBtnBlock, MFComboBox, WinProcs,
  BHAAutomaticApheresis, USGlobalVariant, MFDateTimePicker, MFBitBtnDelete, Variants;

type
  // Test methods for class TMHAAutomaticApheresis

  TestTMHAAutomaticApheresis = class(TTestCase)
  strict private
    FMHAAutomaticApheresis: TMHAAutomaticApheresis;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCheckingBeforeSaving;
  end;

implementation

procedure TestTMHAAutomaticApheresis.SetUp;
begin
  FMHAAutomaticApheresis := TMHAAutomaticApheresis.Create;
end;

procedure TestTMHAAutomaticApheresis.TearDown;
begin
  FMHAAutomaticApheresis.Free;
  FMHAAutomaticApheresis := nil;
end;

procedure TestTMHAAutomaticApheresis.TestCheckingBeforeSaving;
var
  ReturnValue: Boolean;
begin
  ReturnValue := FMHAAutomaticApheresis.CheckingBeforeSaving;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTMHAAutomaticApheresis.Suite);
end.

