unit TestUCheckNull;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Variants, SysUtils, UCheckNull;

type
  // Test methods for class ICheckNull

  TestICheckNull = class(TTestCase)
  strict private
    FICheckNull: ICheckNull;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCheckedValue;
  end;

implementation

procedure TestICheckNull.SetUp;
begin
  FICheckNull:=TCheckNull.Create;
  // TODO: Initialize FICheckNull
end;

procedure TestICheckNull.TearDown;
begin
  FICheckNull := nil;
end;

procedure TestICheckNull.TestCheckedValue;
var
  ReturnValue: Variant;
  CheckValue: Variant;
begin
  CheckValue:=null;
  ReturnValue := FICheckNull.CheckedValue(CheckValue);
  CheckEquals(0,ReturnValue, 'Метод CheckNull.CheckedValue не вернул значение "0" вместо "Null"');
  CheckValue:=1;
  ReturnValue := FICheckNull.CheckedValue(CheckValue);
  CheckEquals(1, ReturnValue, 'Метод CheckNull.CheckedValue вернул не верное значение аргумента');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestICheckNull.Suite);
end.

